### ISSUE TITLE
Background tracking not working

### ISSUE THREAD

**Issue by DausShukor** [radarlabs/capacitor-radar#11]
I had follow the documentation and foreground tracking working fine. But the background tracking not working. Did I miss something? Thanks in advance.

`import { Plugins } from '@capacitor/core';
import 'capacitor-radar';
import { environment } from '../../../environments/environment';

const { RadarPlugin } = Plugins;

@Component({
  selector: 'app-geofence',
  templateUrl: './geofence.page.html',
  styleUrls: ['./geofence.page.scss'],
})
export class GeofencePage implements OnInit {
  result;

  constructor() {
    RadarPlugin.initialize({ publishableKey: environment.radar.android });
  }

  ngOnInit() {
  }

  track() {
    RadarPlugin.trackOnce().then((result) => {
      this.result = result;
    }).catch((err) => {
      if (err.message === 'ERROR_PERMISSIONS') {
        RadarPlugin.requestLocationPermissions({ background: true });
        this.refresh();
      }
    });
    RadarPlugin.startTracking();
  }`

**Comment by nickpatrick** [comment]
Can you explain in detail how you are testing?

**Comment by DausShukor** [comment]
I'm using webhook and I can get result when using foreground tracking. When my app in background, nothing happen. I follow all the configuration and still not working. Can you share some full working example?

**Comment by DausShukor** [comment]
My bad. It's working now. Thank you
