### ISSUE TITLE
How to receive events?

### ISSUE THREAD

**Issue by incognitorobito** [radarlabs/capacitor-radar#12]
How do we receive events from background tracking with this plugin?

I know that webhooks are an option, but I'm specifically referring to on device.

Is it just something like `RadarPlugin.on()`?

**Comment by FahmiChaar** [comment]
Hi @incognitorobito 
Did you find how to receive events ?

**Comment by incognitorobito** [comment]
Nope. :( I just ended up writing my own plugin.
