### ISSUE TITLE
trackVerified method doesn't exist

### ISSUE THREAD

**Issue by Leomhl** [radarlabs/capacitor-radar#81]
trackVerified method doesn't exist on Radar 3.6.0 for capacitor. 
Is there a forecast for this to be resolved?

**Comment by nickpatrick** [comment]
Hey @Leomhl, thanks for flagging. This was exposed in https://github.com/radarlabs/capacitor-radar/releases/tag/3.7.1. Let us know if you have any issues!

cc @brettguenther
